name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write
  packages: write
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tom-abc'
      - name: Release
        run: |
          npm i -D semantic-release @semantic-release/git @semantic-release/changelog conventional-changelog-conventionalcommits
          npm run build
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
